### ISSUE TITLE
Animation bug in RecyclerView

### ISSUE THREAD

**Issue by NewITCorp** [nex3z/NotificationBadge#4]
Hi, thanks for a great work!

May you please check if it is a bug when using it with recyclerview.
Afer adapter is notified, with nbAnimationEnabled = true,
1. All badges in all row are gone after animation mUpdate is ended
2. even adapter.notifyItemChanged(position) but the NB animation still being played in all record at once.

If I changed to Listview, or I put it in TabLayout, it works flawlessly. 
The code inside OnBindViewHolder is only NotificationBadge.setNumber();

thanks

**Comment by nex3z** [comment]
Could you please share your item layout or screenshots? I've tried the following scenario but it seems to be working fine.

![list](https://user-images.githubusercontent.com/5645004/37575667-575ad6d6-2b63-11e8-83df-2cf95ac62c83.gif)

**Comment by NewITCorp** [comment]
yes sure,

![ezgif-5-474b7756a4](https://user-images.githubusercontent.com/26928577/37622606-b3daff76-2bf4-11e8-8571-9db06e8a3fd6.gif)

**Comment by nex3z** [comment]
I've fixed a badge disappearing issue in the 0.3.2 version.

```
implementation 'com.nex3z:notification-badge:0.3.2'
```

But I didn't find why badges in different items would play together upon `notifyItemChanged()`. Maybe there is a `notifyDataSetChanged()` somewhere in your code?

I've attached a demo, hope this could solve your problem.
[Demo.zip](https://github.com/nex3z/NotificationBadge/files/1827922/Demo.zip)

![demo](https://user-images.githubusercontent.com/5645004/37635959-e93cf62a-2c39-11e8-8627-aec5db80ffd1.gif)

If the problem still occurs, please provide a sample project so that I can reproduce the issue. Thanks.

**Comment by NewITCorp** [comment]
Hi, 

1. yes, 0.3.2 fixed the disappearing
2. yes,I intend to add a notifyDatasetChanged() to see what will happen. If I changed it to NotifyItemChanged() it is ok just now.

thanks for a very fast response, and have a nice day!
