### ISSUE TITLE
How to make background smaller?

### ISSUE THREAD

**Issue by fauzynurn** [nex3z/NotificationBadge#7]
I've tried using drawable xml background, but it seems like it has minimum size that i can't resize more. i tried using 10dp x 10dp shape but it didn't get to be smaller.

**Comment by nex3z** [comment]
You can specify the size of the `NotificationBadge` by its `android:layout_width` and `android:layout_height` attributes. For example:

```xml
<com.nex3z.notificationbadge.NotificationBadge
    android:id="@+id/badge"
    android:layout_width="16dp"
    android:layout_height="16dp"
    android:textSize="8sp"
    app:nbBackground="@drawable/badge_bg_with_shadow"
    app:nbMaxTextLength="2"/>
```
![device-2018-06-03-183501](https://user-images.githubusercontent.com/5645004/40885645-38b5084c-675d-11e8-9787-b3e88b00faa7.png)

You can also set `android:layout_width` and `android:layout_height` to `wrap_content` so that the size of the  `NotificationBadge` will depend on the image specified in `app:nbBackground` attribute. For example, with the follwing 10dp x 10dp  `badge_bg_with_shadow.xml` file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="oval" >
            <solid android:color="@color/red"/>
            <size android:width="10dp"
                android:height="10dp" />
        </shape>
    </item>
</layer-list>
```

and the layout:

```xml
<com.nex3z.notificationbadge.NotificationBadge
    android:id="@+id/badge"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:textSize="8sp"
    app:nbBackground="@drawable/badge_bg_with_shadow"
    app:nbMaxTextLength="2"/>
```

You will get:

![device-2018-06-03-184403](https://user-images.githubusercontent.com/5645004/40885703-224c849e-675e-11e8-870b-4b7734ce86c8.png)

**Comment by fauzynurn** [comment]
I have set the Notification Badge width and height wrap_content but no matter what the image background size, it didn't get smaller.

**Comment by Morteza-Rastgoo** [comment]
I did this but the text is not in the center

**Comment by nex3z** [comment]
The [default configuration](https://github.com/nex3z/NotificationBadge/blob/master/notificationbadge/src/main/res/layout/notification_badge.xml#L26) uses center gravity for TextView and its content. 

![2](https://user-images.githubusercontent.com/5645004/64922419-8df94000-d801-11e9-9562-a05234d432df.PNG)

To fully customize the text, you can retrieve the TextView for displaying the number by using

```java
TextView textView = badge.getTextView();
```

and change its layout configuration for a pixel perfect alignment.
